"""Seed the database with reps, routes, shops and a historical GPS trail.

The location history is generated by tracing a breadcrumb trail through each
rep's already-visited shops and inserting one LocationPing every 3 seconds,
exactly as the rep's mobile app would have reported them.
"""
from datetime import datetime, timedelta

from sqlalchemy.orm import Session

from .geo import build_trail
from .models import LocationPing, Rep, Route, Shop

REPS = [
    dict(id="rep1", name="Kamal Perera", avatar="KP", phone="+94 77 123 4567",
         zone="Colombo 3 - Fort", is_active=True),
    dict(id="rep2", name="Niluka Fernando", avatar="NF", phone="+94 71 234 5678",
         zone="Colombo 5 - Havelock", is_active=False),
    dict(id="rep3", name="Suresh Bandara", avatar="SB", phone="+94 76 345 6789",
         zone="Colombo 7 - Cinnamon Gardens", is_active=True),
    dict(id="rep4", name="Priya Wickramasinghe", avatar="PW", phone="+94 78 456 7890",
         zone="Colombo 4 - Bambalapitiya", is_active=True),
]

ROUTES = [
    dict(id="route1", rep_id="rep1", start_time="08:00 AM", estimated_end_time="05:00 PM"),
    dict(id="route2", rep_id="rep2", start_time="08:00 AM", estimated_end_time="04:00 PM"),
    dict(id="route3", rep_id="rep3", start_time="08:00 AM", estimated_end_time="06:00 PM"),
    dict(id="route4", rep_id="rep4", start_time="09:00 AM", estimated_end_time="06:00 PM"),
]

SHOPS = {
    "route1": [
        dict(id="s1_1", name="Lanka Supermart", address="45 Chatham St, Colombo 01",
             lat=6.9344, lng=79.8424, visit_status="visited", visit_time="08:30 AM",
             order_amount=45000, notes="Regular weekly order. Manager Pradeep was available.",
             contact_name="Pradeep Silva", contact_phone="+94 11 234 5678", sequence=1),
        dict(id="s1_2", name="Metro Cash & Carry", address="12 York St, Colombo 01",
             lat=6.9318, lng=79.8445, visit_status="visited", visit_time="09:15 AM",
             order_amount=128000, notes="Bulk order placed. Delivery scheduled for Thursday.",
             contact_name="Ranjith Kumar", contact_phone="+94 11 345 6789", sequence=2),
        dict(id="s1_3", name="Cargills Food City", address="78 Union Pl, Colombo 02",
             lat=6.9271, lng=79.8512, visit_status="visited", visit_time="10:05 AM",
             order_amount=67500, notes="New product range accepted. Will order next week.",
             contact_name="Chaminda Wijeratne", contact_phone="+94 11 456 7890", sequence=3),
        dict(id="s1_4", name="Keells Super", address="23 Galle Rd, Colombo 03",
             lat=6.9198, lng=79.8534, visit_status="visited", visit_time="11:20 AM",
             order_amount=89200, notes="Promotional display arranged.",
             contact_name="Shantha De Silva", contact_phone="+94 11 567 8901", sequence=4),
        dict(id="s1_5", name="Arpico Supercentre", address="56 R A De Mel Mawatha, Colombo 03",
             lat=6.9145, lng=79.8556, visit_status="unvisited", sequence=5),
        dict(id="s1_6", name="Laugfs Supermarket", address="34 Duplication Rd, Colombo 03",
             lat=6.9089, lng=79.8578, visit_status="unvisited", sequence=6),
        dict(id="s1_7", name="Softlogic Glomark", address="90 Galle Rd, Colombo 04",
             lat=6.9012, lng=79.8601, visit_status="unvisited", sequence=7),
    ],
    "route2": [
        dict(id="s2_1", name="Havelock City Mall", address="360 Havelock Rd, Colombo 05",
             lat=6.8967, lng=79.8623, visit_status="visited", visit_time="08:00 AM",
             order_amount=210000, notes="All shelves restocked. Manager very satisfied.",
             contact_name="Anura Dissanayake", contact_phone="+94 11 678 9012", sequence=1),
        dict(id="s2_2", name="Majestic City", address="10 Station Rd, Colombo 04",
             lat=6.8912, lng=79.8598, visit_status="visited", visit_time="09:30 AM",
             order_amount=156000, notes="New seasonal order confirmed.",
             contact_name="Dilrukshi Jayawardena", contact_phone="+94 11 789 0123", sequence=2),
        dict(id="s2_3", name="Liberty Plaza", address="R A De Mel Mawatha, Colombo 03",
             lat=6.9034, lng=79.8567, visit_status="visited", visit_time="10:45 AM",
             order_amount=98500, notes="Promotional materials delivered.",
             contact_name="Tharaka Seneviratne", contact_phone="+94 11 890 1234", sequence=3),
        dict(id="s2_4", name="Crescat Boulevard", address="89 Galle Rd, Colombo 03",
             lat=6.9078, lng=79.8534, visit_status="visited", visit_time="11:30 AM",
             order_amount=175000, notes="Premium shelf space negotiated.",
             contact_name="Sachini Ratnayake", contact_phone="+94 11 901 2345", sequence=4),
        dict(id="s2_5", name="One Galle Face Mall", address="1A Galle Face Green, Colombo 02",
             lat=6.9212, lng=79.8478, visit_status="visited", visit_time="13:00 PM",
             order_amount=320000, notes="Largest single order this month.",
             contact_name="Lahiru Mendis", contact_phone="+94 11 012 3456", sequence=5),
        dict(id="s2_6", name="Colombo City Centre",
             address="Muhandiram Ernest De Silva Mawatha, Colombo 02",
             lat=6.9234, lng=79.8501, visit_status="visited", visit_time="14:30 PM",
             order_amount=145000, notes="Quarterly review completed.",
             contact_name="Pavithra Gunasekara", contact_phone="+94 11 123 4567", sequence=6),
    ],
    "route3": [
        dict(id="s3_1", name="Vijitha Yapa Bookshop", address="402 Galle Rd, Colombo 06",
             lat=6.8823, lng=79.8645, visit_status="visited", visit_time="08:15 AM",
             order_amount=34500, notes="Stationery supplies restocked.",
             contact_name="Nimal Jayasuriya", contact_phone="+94 11 234 5679", sequence=1),
        dict(id="s3_2", name="Barefoot Gallery", address="704 Galle Rd, Colombo 03",
             lat=6.9089, lng=79.8601, visit_status="visited", visit_time="09:45 AM",
             order_amount=67800, notes="Specialty items ordered for gallery shop.",
             contact_name="Amara Perera", contact_phone="+94 11 345 6790", sequence=2),
        dict(id="s3_3", name="Fashion Bug", address="25 Dharmapala Mawatha, Colombo 07",
             lat=6.9112, lng=79.8712, visit_status="visited", visit_time="11:00 AM",
             order_amount=89000, notes="New season collection presented.",
             contact_name="Kasun Wickramaratne", contact_phone="+94 11 456 7891", sequence=3),
        dict(id="s3_4", name="Spa Ceylon", address="37 Dharmapala Mawatha, Colombo 07",
             lat=6.9134, lng=79.8734, visit_status="skipped",
             notes="Manager unavailable. Will revisit tomorrow.", sequence=4),
        dict(id="s3_5", name="Paradise Road Gallery", address="213 Dharmapala Mawatha, Colombo 07",
             lat=6.9156, lng=79.8756, visit_status="unvisited", sequence=5),
        dict(id="s3_6", name="Colombo Tea Traders", address="150 Bauddhaloka Mawatha, Colombo 07",
             lat=6.9178, lng=79.8778, visit_status="unvisited", sequence=6),
        dict(id="s3_7", name="Lanka Tiles Showroom", address="64 Bauddhaloka Mawatha, Colombo 07",
             lat=6.9201, lng=79.8756, visit_status="unvisited", sequence=7),
        dict(id="s3_8", name="Odel Department Store", address="5 Alexandra Pl, Colombo 07",
             lat=6.9145, lng=79.8689, visit_status="unvisited", sequence=8),
    ],
    "route4": [
        dict(id="s4_1", name="Bambalapitiya Supermart", address="250 Galle Rd, Colombo 04",
             lat=6.8812, lng=79.8567, visit_status="visited", visit_time="08:45 AM",
             order_amount=52000, notes="New territory. First visit went well.",
             contact_name="Roshan Wijeratne", contact_phone="+94 11 567 8902", sequence=1),
        dict(id="s4_2", name="Wellawatte Mini Mart", address="120 Galle Rd, Colombo 06",
             lat=6.8756, lng=79.8601, visit_status="unvisited", sequence=2),
        dict(id="s4_3", name="Dehiwala Junction Store", address="45 Galle Rd, Dehiwala",
             lat=6.8678, lng=79.8623, visit_status="unvisited", sequence=3),
        dict(id="s4_4", name="Mount Lavinia Fresh Mart", address="12 Hotel Rd, Mount Lavinia",
             lat=6.8523, lng=79.8656, visit_status="unvisited", sequence=4),
        dict(id="s4_5", name="Ratmalana Traders", address="67 Galle Rd, Ratmalana",
             lat=6.8445, lng=79.8689, visit_status="unvisited", sequence=5),
        dict(id="s4_6", name="Moratuwa City Mart", address="89 Galle Rd, Moratuwa",
             lat=6.8312, lng=79.8712, visit_status="unvisited", sequence=6),
    ],
}

PING_INTERVAL_SECONDS = 3


def seed(db: Session) -> None:
    """Populate an empty database. No-op if reps already exist."""
    if db.query(Rep).count() > 0:
        return

    today = datetime.utcnow().date().isoformat()

    for rep in REPS:
        db.add(Rep(**rep))

    for route in ROUTES:
        db.add(Route(date=today, **route))

    for route_id, shops in SHOPS.items():
        for shop in shops:
            db.add(Shop(route_id=route_id, **shop))

    db.flush()

    # Build a historical GPS trail per rep through their visited shops.
    base_time = datetime.utcnow() - timedelta(hours=1)
    for route in ROUTES:
        shops = SHOPS[route["id"]]
        visited = [
            (s["lat"], s["lng"]) for s in shops if s["visit_status"] == "visited"
        ]
        trail = build_trail(visited)
        for i, (lat, lng) in enumerate(trail):
            db.add(
                LocationPing(
                    rep_id=route["rep_id"],
                    latitude=lat,
                    longitude=lng,
                    recorded_at=base_time + timedelta(seconds=i * PING_INTERVAL_SECONDS),
                )
            )

    db.commit()
